-- Create the hr_documents bucket
INSERT INTO storage.buckets (id, name, public) VALUES ('hr_documents', 'hr_documents', true)
ON CONFLICT (id) DO NOTHING;

-- Policies for storage (Drop if exists first to avoid errors on rerun)
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Auth Insert" ON storage.objects;
DROP POLICY IF EXISTS "Auth Update" ON storage.objects;
DROP POLICY IF EXISTS "Auth Delete" ON storage.objects;

CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'hr_documents');
CREATE POLICY "Auth Insert" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'hr_documents' AND auth.role() = 'authenticated');
CREATE POLICY "Auth Update" ON storage.objects FOR UPDATE WITH CHECK (bucket_id = 'hr_documents' AND auth.role() = 'authenticated');
CREATE POLICY "Auth Delete" ON storage.objects FOR DELETE USING (bucket_id = 'hr_documents' AND auth.role() = 'authenticated');

-- Create employee_documents table
CREATE TABLE IF NOT EXISTS public.employee_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    document_type TEXT NOT NULL, -- e.g., 'NID', 'CV', 'Certificate'
    document_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.employee_documents ENABLE ROW LEVEL SECURITY;

-- Policies for employee_documents
DROP POLICY IF EXISTS "Users can view their own documents" ON public.employee_documents;
DROP POLICY IF EXISTS "Users can insert their own documents" ON public.employee_documents;
DROP POLICY IF EXISTS "Admins can update documents" ON public.employee_documents;
DROP POLICY IF EXISTS "Admins can delete documents" ON public.employee_documents;

CREATE POLICY "Users can view their own documents" ON public.employee_documents FOR SELECT USING (auth.uid() = user_id OR (SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true);
CREATE POLICY "Users can insert their own documents" ON public.employee_documents FOR INSERT WITH CHECK (auth.uid() = user_id OR (SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true);
CREATE POLICY "Admins can update documents" ON public.employee_documents FOR UPDATE USING ((SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true);
CREATE POLICY "Admins can delete documents" ON public.employee_documents FOR DELETE USING ((SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true);

-- Add CV URL to job_applications if it exists
ALTER TABLE public.job_applications ADD COLUMN IF NOT EXISTS cv_url TEXT;
